
INSERT INTO CONF_ROOM VALUES(1, 'roomA');
INSERT INTO CONF_ROOM VALUES(2, 'roomB');
INSERT INTO CONF_ROOM VALUES(3, 'roomC');
INSERT INTO CONF_ROOM VALUES(4, 'roomD');
INSERT INTO CONF_ROOM VALUES(5, 'roomE');
INSERT INTO CONF_ROOM VALUES(6, 'roomF');




